### ISSUE TITLE
quasi-potential code?

### ISSUE THREAD

**Issue by willey2020** [mkm1712/Brahma_model#1]
Hello!Nice work! Congratulations!
Could I ask if the quasi-potential calculation code is in? Thank you so much.

Thanks!

**Comment by mkm1712** [comment]
Hi
Thanks. The codes used for this paper are in this folder including
quasi-potential calculation. You also can obtain the initial source code
from the reference paper that we used for our calculation. It is cited in
the paper.
Best

**Comment by willey2020** [comment]
Thank you so much!!!!
